name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rake:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_FORCE_RUBY_PLATFORM: 1
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7"]
        gemfile: ["gemfiles/rails52.gemfile"]
        bundler: ["2"]
        include:
          - ruby: "2.5"
            gemfile: "gemfiles/rails5001.gemfile"
            bundler: "1"
          - ruby: "2.6"
            gemfile: "gemfiles/rails51.gemfile"
            bundler: "2"
          - ruby: "2.6"
            gemfile: "gemfiles/rspec4rails5.gemfile"
            bundler: "2"
          - ruby: "2.7"
            gemfile: "gemfiles/rspec4rails6.gemfile"
            bundler: "2"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: /home/runner/bundle
        key: bundle-${{ matrix.ruby }}-${{ matrix.gemfile }}-${{ hashFiles('**/*.gemspec') }}-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          bundle-${{ matrix.ruby }}-${{ matrix.gemfile }}-
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: ${{ matrix.bundler }}
    - name: Bundle install
      run: |
        bundle config path /home/runner/bundle
        bundle config --global gemfile ${{ matrix.gemfile }}
        bundle install
        bundle update
    - name: Run RSpec
      run: |
        bundle exec rake
